version: '3.8'

services:
  nearme-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nearme-container
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped